<template>
  <div
    class="bmc full-height"
    style="min-height: inherit"
    :class="{ presentation: showAsPresentation, print: showAsPrint }"
  >
    <draw-surface v-if="layout.showDrawSurface"></draw-surface>
    <note-options />
    <q-linear-progress
      v-if="showAsPresentation && !showAsPrint"
      :value="presentationProgress"
      height="4"
      class="ma-0"
    />
    <div class="credits-own caption">
      Generated by BM|Desginer
      <a href="https://bmdesigner.com" target="_blank">(bmdesigner.com)</a>
    </div>
    <div class="credits caption">
      <a href="https://strategyzer.com/canvas/business-model-canvas" target="_blank"
        >The Business Model Canvas</a
      >
      by
      <a href="http://strategyzer.com" target="_blank">Strategyzer AG</a> is licensed under
      <a href="http://creativecommons.org/licenses/by-sa/3.0" target="_blank">CC BY-SA 3.0</a>
    </div>
    <image-zone
      :allow-click="false"
      class="canvas"
      @image-drop="addNote"
      @click.prevent.stop="addNote($event)"
    >
      <div
        ref="paper"
        class="paper elevation-10"
        :class="{ game: canvas && canvas.info && canvas.info.isGame }"
        data-none="bmc_tmp"
      >
        <q-linear-progress
          v-if="isLoading"
          transition="slide-y-transition"
          class="ma-0"
          indeterminate
          style="z-index: 1"
        ></q-linear-progress>

        <zone
          id="c"
          dropzone-accept=".note-bmc"
          label="Cost Structure"
          style="left: 0; top: 75%; width: 40%; height: 25%"
        >
          <template #icon>
            <q-icon :name="ICONS['c']" />
          </template>
        </zone>
        <zone
          id="pn"
          dropzone-accept=".note-bmc"
          label="Partner Network"
          style="left: 0; top: 0; width: 20%; height: 75%"
        >
          <template #icon>
            <q-icon :name="ICONS['pn']" />
          </template>
        </zone>
        <zone
          id="ka"
          dropzone-accept=".note-bmc"
          label="Key Activities"
          style="left: 20%; top: 0; width: 20%; height: 37.5%"
        >
          <template #icon>
            <q-icon :name="ICONS['ka']" />
          </template>
        </zone>
        <zone
          id="kr"
          dropzone-accept=".note-bmc"
          label="Key Resources"
          style="left: 20%; top: 37.5%; width: 20%; height: 37.5%"
        >
          <template #icon>
            <q-icon :name="ICONS['kr']" />
          </template>
        </zone>
        <zone
          id="vp"
          dropzone-accept=".note-bmc"
          class="zone-highlight"
          :class="{
            'highlight-on': layout.selectedCS && !layout.selectedVP,
            'elevation-10': layout.selectedCS && !layout.selectedVP,
          }"
          label="Value Proposition"
          style="left: 40%; top: 0; width: 20%; height: 75%"
        >
          <template #icon>
            <q-icon :name="ICONS['vp']" />
          </template>
        </zone>
        <zone
          id="cr"
          dropzone-accept=".note-bmc"
          label="Customer Relationships"
          style="left: 60%; top: 0; width: 20%; height: 37.5%"
        >
          <template #icon>
            <q-icon :name="ICONS['cr']" />
          </template>
        </zone>
        <zone
          id="dc"
          dropzone-accept=".note-bmc"
          label="Distribution Channels"
          style="left: 60%; top: 37.5%; width: 20%; height: 37.5%"
        >
          <template #icon>
            <q-icon :name="ICONS['dc']" />
          </template>
        </zone>
        <zone
          id="cs"
          dropzone-accept=".note-bmc"
          class="zone-highlight"
          :class="{
            'highlight-on': !layout.selectedCS && layout.selectedVP,
            'elevation-10': !layout.selectedCS && layout.selectedVP,
          }"
          label="Customer Segments"
          style="left: 80%; top: 0; width: 20%; height: 75%"
        >
          <template #icon>
            <q-icon :name="ICONS['cs']" />
          </template>
        </zone>
        <zone
          id="r"
          dropzone-accept=".note-bmc"
          label="Revenue Streams"
          style="left: 60%; top: 75%; width: 40%; height: 25%"
        >
          <template #icon>
            <q-icon :name="ICONS['r']" />
          </template>
        </zone>
        <div v-if="canvas" class="logo" :style="{ 'background-color': canvas.logoColor }">
          <image-zone
            :allow-click="layout.isEditable"
            :image="canvas.logoImage"
            :color="canvas.logoColor"
            @update:image="canvasInfoUpdate({ logoImage: $event })"
            @update:color="canvasInfoUpdate({ logoColor: $event })"
          ></image-zone>
        </div>
        <div>
          <note
            v-for="note in notesBMC"
            :key="note.$id"
            :value="note"
            class="note-bmc"
            :class="{
              'highlight-on':
                (layout.selectedCS && !layout.selectedVP && note.type === 'vp') ||
                (!layout.selectedCS && layout.selectedVP && note.type === 'cs'),
            }"
            :parent="paper!"
          ></note>
        </div>
      </div>
    </image-zone>
    <vpc></vpc>
    <game-status-bar
      v-if="canvas && canvas.info && canvas.info.isGame"
      @won="showCongrats = true"
    ></game-status-bar>
    <pop-in-text v-if="showCongrats" v-model="showCongrats"></pop-in-text>
    <presentation-controls v-if="showAsPresentation && !showAsPrint"></presentation-controls>
  </div>
</template>

<script setup lang="ts">
import { ref, useTemplateRef, computed, watch, onMounted, onBeforeUnmount, getCurrentInstance } from 'vue'
import debounce from 'lodash.debounce'
import Note from '@/components/bmc/Note.vue'
import Zone from '@/components/bmc/Zone.vue'
import Vpc from '@/components/bmc/VPC.vue'
import PopInText from '@/components/bmc/PopInText.vue'
import GameStatusBar from '@/components/bmc/GameStatusBar.vue'
import DrawSurface from '@/components/bmc/DrawSurface.vue'
import ImageZone from '@/components/bmc/ImageZone.vue'
import NoteOptions from '@/components/bmc/NoteOptions.vue'
import PresentationControls from '@/components/bmc/PresentationControls.vue'
import { storeToRefs } from 'pinia'
import { totalOffset } from '@/utils/dom'
import { ICONS } from '@/utils/constants'
import { useBmcUIStore } from '@/stores/bmc-ui-store'
import { useBMCStore } from '@/stores/bmc-store'
import { useRoute } from 'vue-router'

const route = useRoute()
const instance = getCurrentInstance()

const bmcUiStore = useBmcUIStore()
const { layout } = storeToRefs(bmcUiStore)

const bmcStore = useBMCStore()
const { notesBMC, canvasSettings, canvas } = storeToRefs(bmcStore)
const { noteCreate, zoomNoteKey, canvasInfoUpdate } = bmcStore

let resizeHandler: ReturnType<typeof debounce> | null = null

const isLoading = ref(false)
const showAsPresentation = ref(false)
const showAsPrint = ref(false)
const showCongrats = ref(false)
const paper = useTemplateRef('paper')

const presentationProgress = computed(() => {
  if (!canvas.value || !canvas.value.notesPresentationOrder) {
    return 0
  }
  return (
    ((canvas.value.notesPresentationOrder.indexOf(canvas.value.currentPresentationKey) + 1) * 100) /
    canvas.value.notesPresentationOrder.length
  )
})

const listMode = computed(() => canvasSettings.value.listMode)

watch(listMode, () => {
  // triggers height calculations
  window.dispatchEvent(new Event('resize'))
})

watch(
  () => route.name,
  () => {
    fetchData()
  }
)

watch(
  () => layout.value.presentation,
  (val) => {
    const crowdShortcut = document.getElementById('crowd-shortcut')
    if (val) {
      if (instance?.proxy?.$el) {
        const offset = totalOffset(instance.proxy.$el)
        instance.proxy.$el.style.top = `${offset.top}px`
        instance.proxy.$el.style.left = `${offset.left}px`
        instance.proxy.$el.style.position = 'absolute'
      }
      if (crowdShortcut) {
        crowdShortcut.style.display = 'none'
      }
      setTimeout(() => {
        showAsPresentation.value = true
      }, 0)
    } else {
      showAsPresentation.value = false
      setTimeout(() => {
        if (instance?.proxy?.$el) {
          instance.proxy.$el.style.top = ''
          instance.proxy.$el.style.left = ''
          instance.proxy.$el.style.position = 'relative'
        }
        if (crowdShortcut) {
          crowdShortcut.style.display = 'block'
        }
      }, 500)
    }
  }
)

function handleWindowResize() {
  if (!paper.value || !instance?.proxy?.$el) {
    return
  }
  instance.proxy.$el.style.setProperty('--zoneLabelFontSize', `${paper.value.offsetHeight * 0.02}px`)
  instance.proxy.$el.style.setProperty(
    '--zoneLabelIconFontSize',
    `${paper.value.offsetHeight * 0.03}px`
  )
}

function fetchData() {
  const zoomed = zoomNoteKey(route.query.zoom1 as string) || zoomNoteKey(route.query.zoom2 as string)
  if (!zoomed) {
    layout.value.showVPC = false
  }
  if (resizeHandler) {
    window.removeEventListener('resize', resizeHandler as any)
  }
  resizeHandler = debounce(handleWindowResize, 300)
  window.addEventListener('resize', resizeHandler as any)
  handleWindowResize()
}

function fetchPrintData(id: string) {
  // TODO: Implement print data fetching
  return Promise.resolve()
}

function addNote(e: any) {
  if (!paper.value) return
  const offset = totalOffset(paper.value)
  const noteCenter = {
    x: paper.value.offsetWidth / 15,
    y: 20,
  }
  const x = e.x - noteCenter.x - offset.left
  const y = e.y - noteCenter.y - offset.top

  const note: any = {
    left: x / (paper.value.offsetWidth / 100),
    top: y / (paper.value.offsetHeight / 100),
    listLeft: x / (paper.value.offsetWidth / 100),
    listTop: y / (paper.value.offsetHeight / 100),
    type: 'bmc_tmp',
    colors: canvasSettings.value.lastUsedColors,
    image: e.image,
  }

  if (e.target.classList.contains('zone')) {
    note.type = e.target.getAttribute('id')
  }
  // TODO #56: keep previous setting?
  if (e.image) {
    note.showAsSticky = false
  }
  noteCreate(note)
}

onMounted(() => {
  if (route.name === 'BusinessModelCanvas') {
    fetchData()
    // FIXME
  } else if (route.name === 'print') {
    // fetch data from sessionsid
    fetchPrintData(route.params.id as string).then(() => {
      showAsPresentation.value = true
      showAsPrint.value = true
      handleWindowResize()
      window.dispatchEvent(new Event('resize'))
    })
  }
})

onBeforeUnmount(() => {
  if (resizeHandler) {
    window.removeEventListener('resize', resizeHandler as any)
  }
  // FIXME
  // this.$store.dispatch('unbindCanvas');
})

// TODO: move and generalize for VPC + move to server
/*
function prepareGame() {
  // https://bost.ocks.org/mike/shuffle/
  function shuffle(array) {
    let m = array.length;
    let t;
    let i;

    // While there remain elements to shuffle…
    while (m) {
      // Pick a remaining element…
      m -= 1;
      i = Math.floor(Math.random() * m);

      // And swap it with the current element.
      t = array[m];
      array[m] = array[i];
      array[i] = t;
    }

    return array;
  }
  let it = 0;
  let il = 0;
  const TOP_END = 8;
  const BOTTOM_START = 19;
  const X_INTERVAL = 14;
  const Y_INTERVAL = 18;
  shuffle(notesBMC.value.slice()).forEach((note, i) => {
    if (i > TOP_END && i < BOTTOM_START) {
      if (i % 2 === 1) {
        il = 0;
        it += Y_INTERVAL;
      } else {
        il = 100 + X_INTERVAL;
      }
    }
    if (i === BOTTOM_START) {
      il = 0;
      it = 100 + Y_INTERVAL;
    }
    const left = -X_INTERVAL + Math.random() * 4 + il;
    const top = -Y_INTERVAL + Math.random() * 4 + it;
    il += X_INTERVAL;

    note.left = left;
    note.top = top;
    note.isGame = true;
    note.type_saved = note.type;
    note.type = 'bmc_tmp';
    // TODO: source ref if serverside check
  });
  const canvasValue = Object.assign({}, canvas.value);
  canvasValue.info = Object.assign({}, canvas.value?.info);
  canvasValue.info.name += ' GAME';
  canvasValue.info.isGame = true;
  canvasValue.source = 'bmdesigner';

  function downloadObjectAsJson(exportObj, exportName) {
    const dataStr = `data:text/json;charset=utf-8, ${encodeURIComponent(
      JSON.stringify(exportObj)
    )}`;
    const downloadAnchorNode = document.createElement('a');
    downloadAnchorNode.setAttribute('href', dataStr);
    downloadAnchorNode.setAttribute('download', `${exportName}.json`);
    downloadAnchorNode.click();
    downloadAnchorNode.remove();
  }
  downloadObjectAsJson(canvasValue, canvasValue.info?.name);
}
*/
</script>

<style scoped>
.bmc {
  flex: 1;
  position: relative;
  transition: all 0.5s ease;
  right: 0;
  bottom: 0;
}

.bmc.presentation {
  position: fixed;
  top: 0 !important;
  left: 0 !important;
  right: 0;
  bottom: 0;
  z-index: 3;
  background-color: #424242;
}

.bmc.print .credits-own,
.bmc.print .credits {
  z-index: 99;
  display: block;
}

.bmc.print .paper {
  width: 100vw;
  max-width: 100vw;
  height: 56.25vw;
  max-height: 100vh;
}

.canvas {
  position: absolute;
  left: 0;
  right: 0;
  bottom: 0;
  top: 0;
  display: flex;
  align-content: center;
  justify-content: center;
  flex-direction: column;
  overflow: auto;
}

.paper {
  width: 80vw;
  height: 54.88vw;
  /* height:width ratio = 9/16 = .5625  */
  max-height: calc(100vh - 100px);
  max-width: calc(145.7vh - 100px);
  /* 16/9 = 1.778 */
  min-width: 1024px;
  min-height: 560px;
  margin: auto;
  position: relative;
}

.paper.game {
  width: 60vw;
  height: 34.88vw;
  min-width: 800px;
  min-height: 440px;
  transition: all 0.5s linear;
}

.zone-highlight {
  z-index: 0;
  transition: z-index 0.5s step-end !important;
}

.highlight-on {
  z-index: 1;
  transition: z-index 0.5s step-start !important;
}

.logo {
  position: absolute;
  top: 75%;
  left: 40%;
  width: 20%;
  height: 25%;
  box-shadow: inset 0 0 0px 1px #818181;
  background-color: #fff;
  color: #333;
}

.logo > div {
  position: absolute;
  top: 2px;
  left: 2px;
  right: 2px;
  bottom: 2px;
}

.credits {
  position: absolute;
  bottom: 8px;
  right: 8px;
}

.credits-own {
  position: absolute;
  bottom: 8px;
  left: 8px;
  display: none;
}

.credits-own a,
.credits a {
  text-decoration: none;
}

.bmc.presentation .credits-own a,
.bmc.presentation .credits a {
  color: #9e9e9e;
}

@media (max-width: 1024px) {
  .highlight-on {
    z-index: 0;
  }
}
</style>
